#' Title transform MT variants table to variants*cell/sample matrix
#'
#' @param MT_variants:  the matrix generated by ErrormutMatrix_detect and removed all "Error" MT variants
#'
#' @return a matrix, row is the variant, cloum is the cell/sample
#' @export
#'


MTmutMatrix_refined <- function(MT_variants)
{
	mut_matrix <- tapply(MT_variants$AF, list(MT_variants$ID, MT_variants$sample), function(x) {x} ) ;
	print(paste(nrow(mut_matrix), "variants and", ncol(mut_matrix), "samples were used!") ) ;
	t_index1 <- is.na(mut_matrix) ;
	t.results <- mut_matrix ;
	t.results[t_index1] <- 0 ;
	return(t.results)
}
